[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gnngroups"
version = "0.1.0"
dependencies = []

[project.scripts]
dataop = "gnngroups.scripts.dataOp:main"

[tool.setuptools.packages.find]
where = ["src"]